### ISSUE TITLE
LazyExpression listeners never get notified

### ISSUE THREAD

**Issue by SkytAsul** [Osmerion/Quitte#12] opened 2023-03-21 18:43 UTC
I don't know if I understood lazy expressions incorrectly, but this bugs me:
```java
SimpleIntProperty health = new SimpleIntProperty(20);

LazyIntExpression healthPlus = LazyIntExpression.of(health, i -> i + 20);
healthPlus.addInvalidationListener(obs -> System.out.println("healthPlus invalidated"));
healthPlus.addChangeListener((obs, oldValue, newValue) -> System.out.println("healthPlus changed to " + newValue));

health.set(15);
health.set(10);
System.out.println(health.get()); // change listener notified

health.set(5);
System.out.println(healthPlus.get()); // change listener and invalidation listener notified
```

Shouldn't the invalidation listener be notified for every change in the dependency?

If that is intended behavior, how shall I do to have an expression that notifies its invalidation listener whenever one of its dependency is itself invalidated _but_ this expression's value must not be computed until explicitly asked because it's resource-consuming (that's why I don't want to use a SimpleExpression)?

**Comment by TheMrMilchmann** [comment] 2023-03-23 12:14
Hey @SkytAsul, this is behaving as intended, but I agree with the sentiment that the documentation has room for improvement. Your observations are a consequence of two design decisions:

1. Lazy properties are not evaluated immediately upon creation but only when their values are actually queried. Specifically, this means that (in your case) `healthPlus` is considered to be invalid (`UNINITIALIZED` to be precise) until your last line of code. If you change the value of `health` again (after `healthPlus.get()`), your listener will be notified.
2. `InvalidationListener`s are called when an observable is invalidated. In this case, `healthPlus` is already invalid and is, therefore, technically not invalidated by changes to the dependency `health`.

Let me know if this explanation helps with your issue. Otherwise, I will need more information about your specific use-case.

**Comment by TheMrMilchmann** [comment] 2023-08-10 14:15
Closing as this has been answered. Please don't hesitate to ask if anything is still unclear.

**Closed by TheMrMilchmann** 2023-08-10 14:15 UTC
Labels: a:question
